# YUMI config

XBotInterface:
  urdf_path: "robots/abb-yumi-ros-pkg/yumi_urdf/urdf/yumi.urdf"
  srdf_path: "robots/abb-yumi-ros-pkg/yumi_srdf/srdf/yumi.srdf"
  joint_map_path: "robots/abb-yumi-ros-pkg/yumi_config/joint_map/yumi_ecat_joint_map.yaml"

RobotInterface:
  framework_name: "ROS"
  
ModelInterface:
  model_type: "RBDL"
  is_model_floating_base: "false"
  
RobotInterfaceYARP:
  subclass_name: "RobotInterfaceROS"
  path_to_shared_lib: "libRobotInterfaceROS.so"
  subclass_factory_name: "robot_interface_ros"
  module_prefix: "test_ROS"
  robot_name: "yumi"
  # different config files for module_prefix

ModelInterfaceRBDL:
  subclass_name: "ModelInterfaceRBDL"
  path_to_shared_lib: "libModelInterfaceRBDL.so"
  subclass_factory_name: "model_interface_rbdl"

RobotInterfaceDUMMY:
  subclass_name: "RobotInterfaceDUMMY"
  path_to_shared_lib: "libRobotInterfaceDUMMY.so"
  subclass_factory_name: "robot_interface_dummy"
